### ISSUE TITLE
Differences between postcss-atrule-bem and postcss-bem

### ISSUE THREAD

**Issue by jonathantneal** [tbremer/postcss-atrule-bem#1]
Which differing use-cases are these targeting?

**Comment by tbremer** [comment]
Great question, @jonathantneal. I put off writing this plugin for a while because I was using your `postcss-nesting` and writing out all the classes I wanted. I looked at `postcss-bem`, but didn't care for the API `@component || @descendent || @modifier`, but you're right, from a 30,000ft view these solve very similar problems, **create BEM class names using a known methodology**, but there are a few distinct differences that make these two plugins very different.

### separations of concerns

`atrule-bem` is only concerned with creating BEM components, has nothing to do with namespacing or utilities. Given it’s separation it’s API is simple and semantic.

### naming conventions

`atrule-bem` prefers the names the methodology assigns (block, element, modifier)

### nested modifiers

`atrule-bem` supports deeply nesting:

``` css
/* this */
@block btn {
    @element small {
        @modifier bold {}
    }
}
/* generates */
.btn {}
.btn__small {}
.btn__small--bold {}
```

Where as `postcs-bem` creates:

``` css
/* this */
@component btn {
    @descendent small {
        @modifer bold {}
    }
}
/* generates */
.btn {}
.btn-small {
    @modifer bold {}
}
```

### recursion

Because of it’s narrow focus the actual API for `atrule-bem` runs on a recursive loop that _should_ allow easy updates and modifications to the plugin.
