### ISSUE TITLE
What is new in the v3.1.0?

### ISSUE THREAD

**Issue by fengyuanchen** [tbremer/postcss-atrule-bem#5]
I cannot find any change log, so I have to check out the code commits for the changes...
I think a changelog is really necessary!

**Comment by tbremer** [comment]
You're absolutely right! I have added a changelog and published a patch version.

To answer your question the changes in 3.1.0 are [listed in depth](https://github.com/tbremer/postcss-atrule-bem/blob/master/CHANGELOG.md#310---2017-11-11). But the TLDR; is:

- Opt in support for `shortcut` selectors `@b, @e, @m` instead of `@block, @element, @modifier`
- Opt in support for changing the separators (still defaults to `__` for elements and `--` for modifiers.
- Added Travis test for Node 8
- updated packages
- minor optimizations
- package.json description updates
